/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CelebrateRouteImport } from './routes/celebrate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthedRouteImport } from './routes/admin._authed'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin._authed.index'
import { Route as AdminAuthedSettingsRouteImport } from './routes/admin._authed.settings'
import { Route as AdminAuthedOffersRouteImport } from './routes/admin._authed.offers'
import { Route as AdminAuthedMenuRouteImport } from './routes/admin._authed.menu'
import { Route as AdminAuthedGalleryRouteImport } from './routes/admin._authed.gallery'
import { Route as AdminAuthedCelebrationRequestsRouteImport } from './routes/admin._authed.celebration-requests'
import { Route as AdminAuthedCakeRequestsRouteImport } from './routes/admin._authed.cake-requests'
import { Route as AdminAuthedBusinessInfoRouteImport } from './routes/admin._authed.business-info'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrateRoute = CelebrateRouteImport.update({
  id: '/celebrate',
  path: '/celebrate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedSettingsRoute = AdminAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedOffersRoute = AdminAuthedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedMenuRoute = AdminAuthedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedGalleryRoute = AdminAuthedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedCelebrationRequestsRoute =
  AdminAuthedCelebrationRequestsRouteImport.update({
    id: '/celebration-requests',
    path: '/celebration-requests',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedCakeRequestsRoute = AdminAuthedCakeRequestsRouteImport.update({
  id: '/cake-requests',
  path: '/cake-requests',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedBusinessInfoRoute = AdminAuthedBusinessInfoRouteImport.update({
  id: '/business-info',
  path: '/business-info',
  getParentRoute: () => AdminAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/celebrate': typeof CelebrateRoute
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/business-info': typeof AdminAuthedBusinessInfoRoute
  '/admin/cake-requests': typeof AdminAuthedCakeRequestsRoute
  '/admin/celebration-requests': typeof AdminAuthedCelebrationRequestsRoute
  '/admin/gallery': typeof AdminAuthedGalleryRoute
  '/admin/menu': typeof AdminAuthedMenuRoute
  '/admin/offers': typeof AdminAuthedOffersRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin/': typeof AdminAuthedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/celebrate': typeof CelebrateRoute
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/business-info': typeof AdminAuthedBusinessInfoRoute
  '/admin/cake-requests': typeof AdminAuthedCakeRequestsRoute
  '/admin/celebration-requests': typeof AdminAuthedCelebrationRequestsRoute
  '/admin/gallery': typeof AdminAuthedGalleryRoute
  '/admin/menu': typeof AdminAuthedMenuRoute
  '/admin/offers': typeof AdminAuthedOffersRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin': typeof AdminAuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/celebrate': typeof CelebrateRoute
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_authed/business-info': typeof AdminAuthedBusinessInfoRoute
  '/admin/_authed/cake-requests': typeof AdminAuthedCakeRequestsRoute
  '/admin/_authed/celebration-requests': typeof AdminAuthedCelebrationRequestsRoute
  '/admin/_authed/gallery': typeof AdminAuthedGalleryRoute
  '/admin/_authed/menu': typeof AdminAuthedMenuRoute
  '/admin/_authed/offers': typeof AdminAuthedOffersRoute
  '/admin/_authed/settings': typeof AdminAuthedSettingsRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/celebrate'
    | '/contact'
    | '/customize'
    | '/gallery'
    | '/menu'
    | '/admin'
    | '/admin/login'
    | '/admin/business-info'
    | '/admin/cake-requests'
    | '/admin/celebration-requests'
    | '/admin/gallery'
    | '/admin/menu'
    | '/admin/offers'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/celebrate'
    | '/contact'
    | '/customize'
    | '/gallery'
    | '/menu'
    | '/admin/login'
    | '/admin/business-info'
    | '/admin/cake-requests'
    | '/admin/celebration-requests'
    | '/admin/gallery'
    | '/admin/menu'
    | '/admin/offers'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/celebrate'
    | '/contact'
    | '/customize'
    | '/gallery'
    | '/menu'
    | '/admin/_authed'
    | '/admin/login'
    | '/admin/_authed/business-info'
    | '/admin/_authed/cake-requests'
    | '/admin/_authed/celebration-requests'
    | '/admin/_authed/gallery'
    | '/admin/_authed/menu'
    | '/admin/_authed/offers'
    | '/admin/_authed/settings'
    | '/admin/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CelebrateRoute: typeof CelebrateRoute
  ContactRoute: typeof ContactRoute
  CustomizeRoute: typeof CustomizeRoute
  GalleryRoute: typeof GalleryRoute
  MenuRoute: typeof MenuRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrate': {
      id: '/celebrate'
      path: '/celebrate'
      fullPath: '/celebrate'
      preLoaderRoute: typeof CelebrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/settings': {
      id: '/admin/_authed/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthedSettingsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/offers': {
      id: '/admin/_authed/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminAuthedOffersRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/menu': {
      id: '/admin/_authed/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminAuthedMenuRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/gallery': {
      id: '/admin/_authed/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminAuthedGalleryRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/celebration-requests': {
      id: '/admin/_authed/celebration-requests'
      path: '/celebration-requests'
      fullPath: '/admin/celebration-requests'
      preLoaderRoute: typeof AdminAuthedCelebrationRequestsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/cake-requests': {
      id: '/admin/_authed/cake-requests'
      path: '/cake-requests'
      fullPath: '/admin/cake-requests'
      preLoaderRoute: typeof AdminAuthedCakeRequestsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/business-info': {
      id: '/admin/_authed/business-info'
      path: '/business-info'
      fullPath: '/admin/business-info'
      preLoaderRoute: typeof AdminAuthedBusinessInfoRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedBusinessInfoRoute: typeof AdminAuthedBusinessInfoRoute
  AdminAuthedCakeRequestsRoute: typeof AdminAuthedCakeRequestsRoute
  AdminAuthedCelebrationRequestsRoute: typeof AdminAuthedCelebrationRequestsRoute
  AdminAuthedGalleryRoute: typeof AdminAuthedGalleryRoute
  AdminAuthedMenuRoute: typeof AdminAuthedMenuRoute
  AdminAuthedOffersRoute: typeof AdminAuthedOffersRoute
  AdminAuthedSettingsRoute: typeof AdminAuthedSettingsRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedBusinessInfoRoute: AdminAuthedBusinessInfoRoute,
  AdminAuthedCakeRequestsRoute: AdminAuthedCakeRequestsRoute,
  AdminAuthedCelebrationRequestsRoute: AdminAuthedCelebrationRequestsRoute,
  AdminAuthedGalleryRoute: AdminAuthedGalleryRoute,
  AdminAuthedMenuRoute: AdminAuthedMenuRoute,
  AdminAuthedOffersRoute: AdminAuthedOffersRoute,
  AdminAuthedSettingsRoute: AdminAuthedSettingsRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CelebrateRoute: CelebrateRoute,
  ContactRoute: ContactRoute,
  CustomizeRoute: CustomizeRoute,
  GalleryRoute: GalleryRoute,
  MenuRoute: MenuRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
